// export const videoAssets = {
//   alif: require('./assets/videos/alif.mp4'),
//   ba: require('./assets/videos/ba.mp4'),
//   ta: require('./assets/videos/ta.mp4'),
//   tha: require('./assets/videos/tha.mp4'),
//   jim: require('./assets/videos/jim.mp4'),
//   ha: require('./assets/videos/ha.mp4'),
//   kha: require('./assets/videos/kha.mp4'),
//   dal: require('./assets/videos/dal.mp4'),
//   dhal: require('./assets/videos/dhal.mp4'),
//   ra: require('./assets/videos/ra.mp4'),
//   zay: require('./assets/videos/zay.mp4'),
//   sin: require('./assets/videos/sin.mp4'),
//   shin: require('./assets/videos/shin.mp4'),
//   sad: require('./assets/videos/sad.mp4'),
//   dad: require('./assets/videos/dad.mp4'),
//   ta2: require('./assets/videos/ta2.mp4'),
//   dha2: require('./assets/videos/dha2.mp4'),
//   ayn: require('./assets/videos/ayn.mp4'),
//   ghayn: require('./assets/videos/ghayn.mp4'),
//   fa: require('./assets/videos/fa.mp4'),
//   qaf: require('./assets/videos/qaf.mp4'),
//   kaf: require('./assets/videos/kaf.mp4'),
//   lam: require('./assets/videos/lam.mp4'),
//   mim: require('./assets/videos/mim.mp4'),
//   nun: require('./assets/videos/nun.mp4'),
//   ha2: require('./assets/videos/ha2.mp4'),
//   waw: require('./assets/videos/waw.mp4'),
//   ya: require('./assets/videos/ya.mp4')
// };
// videoAssets.js
const dummyVideo = require('./assets/videos/dummy.mp4');

export const videoAssets = {
  alif: dummyVideo,
  ba: dummyVideo,
  ta: dummyVideo,
  tha: dummyVideo,
  jim: dummyVideo,
  ha: dummyVideo,
  kha: dummyVideo,
  dal: dummyVideo,
  dhal: dummyVideo,
  ra: dummyVideo,
  zay: dummyVideo,
  sin: dummyVideo,
  shin: dummyVideo,
  sad: dummyVideo,
  dad: dummyVideo,
  ta2: dummyVideo,
  dha2: dummyVideo,
  ayn: dummyVideo,
  ghayn: dummyVideo,
  fa: dummyVideo,
  qaf: dummyVideo,
  kaf: dummyVideo,
  lam: dummyVideo,
  mim: dummyVideo,
  nun: dummyVideo,
  ha2: dummyVideo,
  waw: dummyVideo,
  ya: dummyVideo
};